# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class AmbiguityResult(BaseModel):
    has_missing_color: typing.Optional[bool] = Field(default=None, description='True if any block placement lacks a specified color')
    has_missing_count: typing.Optional[bool] = Field(default=None, description='True if any block placement lacks a specified count/number')
    missing_color_phrase: typing.Optional[str] = Field(default=None, description='The phrase that is missing a color, or empty string')
    missing_count_phrase: typing.Optional[str] = Field(default=None, description='The phrase that is missing a count, or empty string')
    suggested_color_question: typing.Optional[str] = Field(default=None, description='Question to ask about the missing color, or empty string')
    suggested_count_question: typing.Optional[str] = Field(default=None, description='Question to ask about the missing count, or empty string')
    inferred_color: typing.Optional[str] = Field(default=None, description='Best guess color if we had to guess, based on context')
    inferred_count: typing.Optional[int] = Field(default=None, description='Best guess count if we had to guess, based on context (default 3)')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of why ambiguity was or was not detected')

class BuildPlan(BaseModel):
    steps: typing.List["BuildStep"] = Field(description='Ordered list of atomic build steps')

class BuildStep(BaseModel):
    action: typing.Optional[types.BuildAction] = None
    color: typing.Optional[str] = Field(default=None, description='Block color (capitalized). Use \'Uncolored\' if not specified in instruction.')
    count: typing.Optional[int] = Field(default=None, description='Number of blocks. Use 0 if not specified in instruction (means \'Uncounted\').')
    position: typing.Optional["Position"] = Field(default=None, description='Where to place blocks (x,z). Y is auto-computed.')
    direction: typing.Optional[types.Direction] = Field(default=None, description='Direction for extend_row or place_relative. Null if not applicable.')
    reference: typing.Optional[str] = Field(default=None, description='Reference to another block for place_relative, e.g. \'Red_block_at_0_0\'. Null if not applicable.')

class Position(BaseModel):
    x: typing.Optional[int] = Field(default=None, description='X coordinate. Valid: -400,-300,-200,-100,0,100,200,300,400')
    z: typing.Optional[int] = Field(default=None, description='Z coordinate. Valid: -400,-300,-200,-100,0,100,200,300,400')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
