# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class BuildAction(str, Enum):
    Stack = "Stack"
    Place = "Place"
    PlaceRelative = "PlaceRelative"
    ExtendRow = "ExtendRow"
    PlaceAtCorners = "PlaceAtCorners"

class Direction(str, Enum):
    Right = "Right"
    Left = "Left"
    Front = "Front"
    Behind = "Behind"

# #########################################################################
# Generated classes (4)
# #########################################################################

class AmbiguityResult(BaseModel):
    has_missing_color: bool = Field(description='True if any block placement lacks a specified color')
    has_missing_count: bool = Field(description='True if any block placement lacks a specified count/number')
    missing_color_phrase: str = Field(description='The phrase that is missing a color, or empty string')
    missing_count_phrase: str = Field(description='The phrase that is missing a count, or empty string')
    suggested_color_question: str = Field(description='Question to ask about the missing color, or empty string')
    suggested_count_question: str = Field(description='Question to ask about the missing count, or empty string')
    inferred_color: str = Field(description='Best guess color if we had to guess, based on context')
    inferred_count: int = Field(description='Best guess count if we had to guess, based on context (default 3)')
    reasoning: str = Field(description='Brief explanation of why ambiguity was or was not detected')

class BuildPlan(BaseModel):
    steps: typing.List["BuildStep"] = Field(description='Ordered list of atomic build steps')

class BuildStep(BaseModel):
    action: BuildAction
    color: str = Field(description='Block color (capitalized). Use \'Uncolored\' if not specified in instruction.')
    count: int = Field(description='Number of blocks. Use 0 if not specified in instruction (means \'Uncounted\').')
    position: "Position" = Field(description='Where to place blocks (x,z). Y is auto-computed.')
    direction: typing.Optional[Direction] = Field(default=None, description='Direction for extend_row or place_relative. Null if not applicable.')
    reference: typing.Optional[str] = Field(default=None, description='Reference to another block for place_relative, e.g. \'Red_block_at_0_0\'. Null if not applicable.')

class Position(BaseModel):
    x: int = Field(description='X coordinate. Valid: -400,-300,-200,-100,0,100,200,300,400')
    z: int = Field(description='Z coordinate. Valid: -400,-300,-200,-100,0,100,200,300,400')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
