# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AmbiguityResult": types.AmbiguityResult,
    "stream_types.AmbiguityResult": stream_types.AmbiguityResult,

    "types.BuildPlan": types.BuildPlan,
    "stream_types.BuildPlan": stream_types.BuildPlan,

    "types.BuildStep": types.BuildStep,
    "stream_types.BuildStep": stream_types.BuildStep,

    "types.Position": types.Position,
    "stream_types.Position": stream_types.Position,


    "types.BuildAction": types.BuildAction,

    "types.Direction": types.Direction,

}